### ISSUE TITLE
train_best.py ERROR！

### ISSUE THREAD

**Issue by goodboyl** [davidhin/linevd#11]
May I ask if the data in "before" is used at "①", but **all the data** in "before" is vulnerable, i.e. **Vul=1**. However, when the part with "**Vul=0**" is selected in "②", the result is "len (nonvul)**=0**".
![图片1](https://github.com/davidhin/linevd/assets/54784464/f6e6760b-c9d5-44aa-be5a-254abe5f266c)

And the following **error** occurs, it means the "nonvul" is **empty**~
![屏幕截图 2024-03-14 162705](https://github.com/davidhin/linevd/assets/54784464/bbae60f5-eccf-46b3-a586-f5f733ef5899)

May I ask if there is a problem with my understanding? Or please tell me how to handle it.🥹

**Comment by DavideParo** [comment]
@goodboyl Did you happen to resolve that issue?
