### ISSUE TITLE
main.sif missing and google drive links 404

### ISSUE THREAD

**Issue by NikolasBielski** [davidhin/linevd#2]
Thanks for sharing the code for your paper. I'm trying to run this but main.sif is missing and the google drive links to data are not found.

**Comment by davidhin** [comment]
I've updated get_data.sh (Haven't tested it though). I've unfortunately lost access to that Google Drive account, so I just tried to guess the version of Joern that I used based on the approximate date. Also, the sample data is no longer available, but that is only used for testing anyway. `main.sif` is generated by Singularity if it runs successfully.
