### ISSUE TITLE
some problem about "gitdiff" in git.py

### ISSUE THREAD

**Issue by GuoXinrong** [davidhin/linevd#3]

**Comment by GuoXinrong** [comment]
Hi @davidhin ,
when I run the method **bigvul()** in [/linevd/sastvd/helpers/datasets.py](url)  using the dataset "MSR_data_cleaned.csv",I met some problem ,I find that the output of the  **gitdiff()** in  [/linevd/sastvd/helpers/git.py](url) is `(b'', b'/bin/sh: 1: singularity: not found\n')` ,I guess it means that the patch is '',so the following method can not continue to extract the **diff,added,removed** infomation(using**md_lines(patch: str)**), or maybe the problem is caused because I didn't use the singularity tool?
I am looking forward to your reply.

**Comment by davidhin** [comment]
Most of the scripts have only been run using singularity. In particular, that error is likely related to this function: https://github.com/davidhin/linevd/blob/main/sastvd/__init__.py#L102. Singularity was used for the purpose of ensuring that the code is able to be run on multiple devices consistently, instructions can be found at https://sylabs.io/guides/3.5/user-guide/quick_start.html

**Comment by GuoXinrong** [comment]
HI @davidhin ，
I use the singularity to run the `sudo singularity build main.sif Singularity`,but it takes a long time and I often failed to download the joern ,and it often cause fatal so that the main.sif doc can't be build.**So I want to ask for the man.sif that you have already produced when you run your project** .
In other words, I find `the environment can be built using [Singularity](https://sylabs.io/singularity/), or by following / following the commands in the Singularity file. ` in the readme.txt, so I run the commands in the Singularity file to build my own conda environment, and I encounter the problem I mentioned above.
Looking forward to your reply.

**Comment by GuoXinrong** [comment]
Hi,@davidhin
I use singularity to build the man.sif,but I encounter this problem,I can't figure out how to solve it.
![E)A`%0Q}$55STRCU{7PY5LO](https://user-images.githubusercontent.com/41418654/168518323-b333e69c-2786-494f-b817-f569d00b23fb.png)

**Comment by davidhin** [comment]
Maybe try running `singularity run -H /data/xinrongguo/linevd main.sif -p initialise` instead. 

You can also try and skip singularity, and try removing the lines:
https://github.com/davidhin/linevd/blob/main/sastvd/__init__.py#L110-L112
and
https://github.com/davidhin/linevd/blob/main/sastvd/__init__.py#L125-L127

If not, then I'm not too sure of the issue. As I'm quite busy this week, may not be able to take a thorough look until later

**Comment by GuoXinrong** [comment]
Thank you very much ,it works!

**Comment by GuoXinrong** [comment]
Sorry to disturb you again ,I try and skip singularity, and use my native command `CUDA_VISIBLE_DEVICES=0 python3 train_best.py` instead of `singularity exec --nv main.sif python sastvd/scripts/train_best.py` (the third command in readme。txt),but I encounter the "git" problem:
![Z8W}2JBJW1WZ7Z}H1I4@Q@S](https://user-images.githubusercontent.com/41418654/168998541-5c56c904-7fdd-49e5-9d1a-a2de4aa2629e.png)
But I didn't find the code related to "git"

**Comment by 123zcy** [comment]
> _No description provide
请问可以加个联系方式请教一下吗？

**Comment by 123zcy** [comment]
> Thank you very much ,it works!

请问可以加个联系方式请教一下吗？
